class ModelAsmaulHusna {
  final int number;
  final String latin;
  final String arabic;
  final String translationId;

  const ModelAsmaulHusna({
    required this.number,
    required this.latin,
    required this.arabic,
    required this.translationId,
  });
}

class AsmaulHusnaData {
  static const List<ModelAsmaulHusna> list = [
    ModelAsmaulHusna(
      number: 1,
      latin: "Ar-Rahman",
      arabic: "الرَّحْمَنُ",
      translationId: "Yang Maha Pengasih",
    ),
    ModelAsmaulHusna(
      number: 2,
      latin: "Ar-Rahim",
      arabic: "الرَّحِيمُ",
      translationId: "Yang Maha Penyayang",
    ),
    ModelAsmaulHusna(
      number: 3,
      latin: "Al-Malik",
      arabic: "الْمَلِكُ",
      translationId: "Yang Maha Merajai",
    ),
    ModelAsmaulHusna(
      number: 4,
      latin: "Al-Quddus",
      arabic: "الْقُدُّوسُ",
      translationId: "Yang Maha Suci",
    ),
    ModelAsmaulHusna(
      number: 5,
      latin: "As-Salam",
      arabic: "السَّلاَمُ",
      translationId: "Yang Maha Memberi Kesejahteraan",
    ),
    ModelAsmaulHusna(
      number: 6,
      latin: "Al-Mu'min",
      arabic: "الْمُؤْمِنُ",
      translationId: "Yang Maha Memberi Keamanan",
    ),
    ModelAsmaulHusna(
      number: 7,
      latin: "Al-Muhaimin",
      arabic: "الْمُهَيْمِنُ",
      translationId: "Yang Maha Memelihara",
    ),
    ModelAsmaulHusna(
      number: 8,
      latin: "Al-Aziz",
      arabic: "الْعَزِيزُ",
      translationId: "Yang Maha Perkasa",
    ),
    ModelAsmaulHusna(
      number: 9,
      latin: "Al-Jabbar",
      arabic: "الْجَبَّارُ",
      translationId: "Yang Memiliki Mutlak Kegagahan",
    ),
    ModelAsmaulHusna(
      number: 10,
      latin: "Al-Mutakabbir",
      arabic: "الْمُتَكَبِّرُ",
      translationId: "Yang Maha Megah",
    ),
    ModelAsmaulHusna(
      number: 11,
      latin: "Al-Khaliq",
      arabic: "الْخَالِقُ",
      translationId: "Yang Maha Pencipta",
    ),
    ModelAsmaulHusna(
      number: 12,
      latin: "Al-Bari'",
      arabic: "الْبَارِئُ",
      translationId: "Yang Maha Melepaskan",
    ),
    ModelAsmaulHusna(
      number: 13,
      latin: "Al-Mushawwir",
      arabic: "الْمُصَوِّرُ",
      translationId: "Yang Maha Membentuk Rupa",
    ),
    ModelAsmaulHusna(
      number: 14,
      latin: "Al-Ghaffar",
      arabic: "الْغَفَّارُ",
      translationId: "Yang Maha Pengampun",
    ),
    ModelAsmaulHusna(
      number: 15,
      latin: "Al-Qahhar",
      arabic: "الْقَهَّارُ",
      translationId: "Yang Maha Memaksa",
    ),
    ModelAsmaulHusna(
      number: 16,
      latin: "Al-Wahhab",
      arabic: "الْوَهَّابُ",
      translationId: "Yang Maha Pemberi Karunia",
    ),
    ModelAsmaulHusna(
      number: 17,
      latin: "Ar-Razzaq",
      arabic: "الرَّزَّاقُ",
      translationId: "Yang Maha Pemberi Rezeki",
    ),
    ModelAsmaulHusna(
      number: 18,
      latin: "Al-Fattah",
      arabic: "الْفَتَّاحُ",
      translationId: "Yang Maha Pembuka Rahmat",
    ),
    ModelAsmaulHusna(
      number: 19,
      latin: "Al-'Alim",
      arabic: "الْعَلِيمُ",
      translationId: "Yang Maha Mengetahui",
    ),
    ModelAsmaulHusna(
      number: 20,
      latin: "Al-Qabidh",
      arabic: "الْقَابِضُ",
      translationId: "Yang Maha Menyempitkan",
    ),
    ModelAsmaulHusna(
      number: 21,
      latin: "Al-Basith",
      arabic: "الْبَاسِطُ",
      translationId: "Yang Maha Melapangkan",
    ),
    ModelAsmaulHusna(
      number: 22,
      latin: "Al-Khafidh",
      arabic: "الْخَافِضُ",
      translationId: "Yang Maha Merendahkan",
    ),
    ModelAsmaulHusna(
      number: 23,
      latin: "Ar-Rafi'",
      arabic: "الرَّافِعُ",
      translationId: "Yang Maha Meninggikan",
    ),
    ModelAsmaulHusna(
      number: 24,
      latin: "Al-Mu'izz",
      arabic: "الْمُعِزُّ",
      translationId: "Yang Maha Memuliakan",
    ),
    ModelAsmaulHusna(
      number: 25,
      latin: "Al-Mudzill",
      arabic: "المُذِلُّ",
      translationId: "Yang Maha Menghinakan",
    ),
    ModelAsmaulHusna(
      number: 26,
      latin: "As-Sami'",
      arabic: "السَّمِيعُ",
      translationId: "Yang Maha Mendengar",
    ),
    ModelAsmaulHusna(
      number: 27,
      latin: "Al-Bashir",
      arabic: "الْبَصِيرُ",
      translationId: "Yang Maha Melihat",
    ),
    ModelAsmaulHusna(
      number: 28,
      latin: "Al-Hakam",
      arabic: "الْحَكَمُ",
      translationId: "Yang Maha Menetapkan",
    ),
    ModelAsmaulHusna(
      number: 29,
      latin: "Al-'Adl",
      arabic: "الْعَدْلُ",
      translationId: "Yang Maha Adil",
    ),
    ModelAsmaulHusna(
      number: 30,
      latin: "Al-Lathif",
      arabic: "اللَّطِيفُ",
      translationId: "Yang Maha Lembut",
    ),
    ModelAsmaulHusna(
      number: 31,
      latin: "Al-Khabir",
      arabic: "الْخَبِيرُ",
      translationId: "Yang Maha Mengenal",
    ),
    ModelAsmaulHusna(
      number: 32,
      latin: "Al-Halim",
      arabic: "الْحَلِيمُ",
      translationId: "Yang Maha Penyantun",
    ),
    ModelAsmaulHusna(
      number: 33,
      latin: "Al-'Azhim",
      arabic: "الْعَظِيمُ",
      translationId: "Yang Maha Agung",
    ),
    ModelAsmaulHusna(
      number: 34,
      latin: "Al-Ghafur",
      arabic: "الْغَفُورُ",
      translationId: "Yang Maha Pengampun",
    ),
    ModelAsmaulHusna(
      number: 35,
      latin: "Asy-Syakur",
      arabic: "الشَّكُورُ",
      translationId: "Yang Maha Pembalas Budi",
    ),
    ModelAsmaulHusna(
      number: 36,
      latin: "Al-'Aliyy",
      arabic: "الْعَلِيُّ",
      translationId: "Yang Maha Tinggi",
    ),
    ModelAsmaulHusna(
      number: 37,
      latin: "Al-Kabir",
      arabic: "الْكَبِيرُ",
      translationId: "Yang Maha Besar",
    ),
    ModelAsmaulHusna(
      number: 38,
      latin: "Al-Hafizh",
      arabic: "الْحَفِيظُ",
      translationId: "Yang Maha Memelihara",
    ),
    ModelAsmaulHusna(
      number: 39,
      latin: "Al-Muqit",
      arabic: "المُقِيتُ",
      translationId: "Yang Maha Pemberi Kecukupan",
    ),
    ModelAsmaulHusna(
      number: 40,
      latin: "Al-Hasib",
      arabic: "الْحسِيبُ",
      translationId: "Yang Maha Membuat Perhitungan",
    ),
    ModelAsmaulHusna(
      number: 41,
      latin: "Al-Jalil",
      arabic: "الْجَلِيلُ",
      translationId: "Yang Maha Mulia",
    ),
    ModelAsmaulHusna(
      number: 42,
      latin: "Al-Karim",
      arabic: "الْكَرِيمُ",
      translationId: "Yang Maha Pemurah",
    ),
    ModelAsmaulHusna(
      number: 43,
      latin: "Ar-Raqib",
      arabic: "الرَّقِيبُ",
      translationId: "Yang Maha Mengawasi",
    ),
    ModelAsmaulHusna(
      number: 44,
      latin: "Al-Mujib",
      arabic: "الْمُجِيبُ",
      translationId: "Yang Maha Mengabulkan",
    ),
    ModelAsmaulHusna(
      number: 45,
      latin: "Al-Wasi'",
      arabic: "الْوَاسِعُ",
      translationId: "Yang Maha Luas",
    ),
    ModelAsmaulHusna(
      number: 46,
      latin: "Al-Hakim",
      arabic: "الْحَكِيمُ",
      translationId: "Yang Maha Bijaksana",
    ),
    ModelAsmaulHusna(
      number: 47,
      latin: "Al-Wadud",
      arabic: "الْوَدُودُ",
      translationId: "Yang Maha Mengasihi",
    ),
    ModelAsmaulHusna(
      number: 48,
      latin: "Al-Majid",
      arabic: "الْمَجِيدُ",
      translationId: "Yang Maha Mulia",
    ),
    ModelAsmaulHusna(
      number: 49,
      latin: "Al-Ba'its",
      arabic: "الْبَاعِثُ",
      translationId: "Yang Maha Membangkitkan",
    ),
    ModelAsmaulHusna(
      number: 50,
      latin: "Asy-Syahid",
      arabic: "الشَّهِيدُ",
      translationId: "Yang Maha Menyaksikan",
    ),
    ModelAsmaulHusna(
      number: 51,
      latin: "Al-Haqq",
      arabic: "الْحَقُّ",
      translationId: "Yang Maha Benar",
    ),
    ModelAsmaulHusna(
      number: 52,
      latin: "Al-Wakil",
      arabic: "الْوَكِيلُ",
      translationId: "Yang Maha Memelihara",
    ),
    ModelAsmaulHusna(
      number: 53,
      latin: "Al-Qawiyyu",
      arabic: "الْقَوِيُّ",
      translationId: "Yang Maha Kuat",
    ),
    ModelAsmaulHusna(
      number: 54,
      latin: "Al-Matin",
      arabic: "الْمَتِينُ",
      translationId: "Yang Maha Kokoh",
    ),
    ModelAsmaulHusna(
      number: 55,
      latin: "Al-Waliyy",
      arabic: "الْوَلِيُّ",
      translationId: "Yang Maha Melindungi",
    ),
    ModelAsmaulHusna(
      number: 56,
      latin: "Al-Hamid",
      arabic: "الْحَمِيدُ",
      translationId: "Yang Maha Terpuji",
    ),
    ModelAsmaulHusna(
      number: 57,
      latin: "Al-Muhshi",
      arabic: "الْمُحْصِي",
      translationId: "Yang Maha Menghitung",
    ),
    ModelAsmaulHusna(
      number: 58,
      latin: "Al-Mubdi'",
      arabic: "الْمُبْدِئُ",
      translationId: "Yang Maha Memulai",
    ),
    ModelAsmaulHusna(
      number: 59,
      latin: "Al-Mu'id",
      arabic: "الْمُعِيدُ",
      translationId: "Yang Maha Mengembalikan Kehidupan",
    ),
    ModelAsmaulHusna(
      number: 60,
      latin: "Al-Muhyi",
      arabic: "الْمُحْيِي",
      translationId: "Yang Maha Menghidupkan",
    ),
    ModelAsmaulHusna(
      number: 61,
      latin: "Al-Mumit",
      arabic: "الْمُمِيتُ",
      translationId: "Yang Maha Mematikan",
    ),
    ModelAsmaulHusna(
      number: 62,
      latin: "Al-Hayyu",
      arabic: "الْحَيُّ",
      translationId: "Yang Maha Hidup",
    ),
    ModelAsmaulHusna(
      number: 63,
      latin: "Al-Qayyum",
      arabic: "الْقَيُّومُ",
      translationId: "Yang Maha Mandiri",
    ),
    ModelAsmaulHusna(
      number: 64,
      latin: "Al-Wajid",
      arabic: "الْوَاجِدُ",
      translationId: "Yang Maha Penemu",
    ),
    ModelAsmaulHusna(
      number: 65,
      latin: "Al-Majid",
      arabic: "الْمَاجِدُ",
      translationId: "Yang Maha Mulia",
    ),
    ModelAsmaulHusna(
      number: 66,
      latin: "Al-Wahid",
      arabic: "الْوَاحِدُ",
      translationId: "Yang Maha Tunggal",
    ),
    ModelAsmaulHusna(
      number: 67,
      latin: "Al-Ahad",
      arabic: "الأَحَدُ",
      translationId: "Yang Maha Esa",
    ),
    ModelAsmaulHusna(
      number: 68,
      latin: "Ash-Shamad",
      arabic: "الصَّمَدُ",
      translationId: "Yang Maha Dibutuhkan",
    ),
    ModelAsmaulHusna(
      number: 69,
      latin: "Al-Qadir",
      arabic: "الْقَادِرُ",
      translationId: "Yang Maha Menentukan",
    ),
    ModelAsmaulHusna(
      number: 70,
      latin: "Al-Muqtadir",
      arabic: "الْمُقْتَدِرُ",
      translationId: "Yang Maha Berkuasa",
    ),
    ModelAsmaulHusna(
      number: 71,
      latin: "Al-Muqaddim",
      arabic: "الْمُقَدِّمُ",
      translationId: "Yang Maha Mendahulukan",
    ),
    ModelAsmaulHusna(
      number: 72,
      latin: "Al-Mu'akhkhir",
      arabic: "الْمُؤَخِّرُ",
      translationId: "Yang Maha Mengakhirkan",
    ),
    ModelAsmaulHusna(
      number: 73,
      latin: "Al-Awwal",
      arabic: "الأوَّلُ",
      translationId: "Yang Maha Awal",
    ),
    ModelAsmaulHusna(
      number: 74,
      latin: "Al-Akhir",
      arabic: "الآخِرُ",
      translationId: "Yang Maha Akhir",
    ),
    ModelAsmaulHusna(
      number: 75,
      latin: "Azh-Zhahir",
      arabic: "الظَّاهِرُ",
      translationId: "Yang Maha Nyata",
    ),
    ModelAsmaulHusna(
      number: 76,
      latin: "Al-Bathin",
      arabic: "الْبَاطِنُ",
      translationId: "Yang Maha Ghaib",
    ),
    ModelAsmaulHusna(
      number: 77,
      latin: "Al-Wali",
      arabic: "الْوَالِي",
      translationId: "Yang Maha Memerintah",
    ),
    ModelAsmaulHusna(
      number: 78,
      latin: "Al-Muta'ali",
      arabic: "الْمُتَعَالِي",
      translationId: "Yang Maha Tinggi",
    ),
    ModelAsmaulHusna(
      number: 79,
      latin: "Al-Barr",
      arabic: "الْبَرُّ",
      translationId: "Yang Maha Penderma",
    ),
    ModelAsmaulHusna(
      number: 80,
      latin: "At-Tawwab",
      arabic: "التَّوَّابُ",
      translationId: "Yang Maha Penerima Taubat",
    ),
    ModelAsmaulHusna(
      number: 81,
      latin: "Al-Muntaqim",
      arabic: "الْمُنْتَقِمُ",
      translationId: "Yang Maha Pemberi Balasan",
    ),
    ModelAsmaulHusna(
      number: 82,
      latin: "Al-'Afuww",
      arabic: "العَفُوُّ",
      translationId: "Yang Maha Pemaaf",
    ),
    ModelAsmaulHusna(
      number: 83,
      latin: "Ar-Ra'uf",
      arabic: "الرَّؤُوفُ",
      translationId: "Yang Maha Pengasuh",
    ),
    ModelAsmaulHusna(
      number: 84,
      latin: "Malikul Mulk",
      arabic: "مَالِكُ الْمُلْكِ",
      translationId: "Penguasa Kerajaan Semesta",
    ),
    ModelAsmaulHusna(
      number: 85,
      latin: "Dzul Jalali Wal Ikram",
      arabic: "ذُوالْجَلاَلِ وَالإكْرَامِ",
      translationId: "Pemilik Kebesaran dan Kemuliaan",
    ),
    ModelAsmaulHusna(
      number: 86,
      latin: "Al-Muqsith",
      arabic: "الْمُقْسِطُ",
      translationId: "Yang Maha Pemberi Keadilan",
    ),
    ModelAsmaulHusna(
      number: 87,
      latin: "Al-Jami'",
      arabic: "الْجَامِعُ",
      translationId: "Yang Maha Mengumpulkan",
    ),
    ModelAsmaulHusna(
      number: 88,
      latin: "Al-Ghaniyy",
      arabic: "الْغَنِيُّ",
      translationId: "Yang Maha Kaya",
    ),
    ModelAsmaulHusna(
      number: 89,
      latin: "Al-Mughni",
      arabic: "الْمُغْنِي",
      translationId: "Yang Maha Pemberi Kekayaan",
    ),
    ModelAsmaulHusna(
      number: 90,
      latin: "Al-Mani'",
      arabic: "الْمَانِعُ",
      translationId: "Yang Maha Mencegah",
    ),
    ModelAsmaulHusna(
      number: 91,
      latin: "Adh-Dharr",
      arabic: "الضَّارَّ",
      translationId: "Yang Maha Penimpa Kemudharatan",
    ),
    ModelAsmaulHusna(
      number: 92,
      latin: "An-Nafi'",
      arabic: "النَّافِعُ",
      translationId: "Yang Maha Memberi Manfaat",
    ),
    ModelAsmaulHusna(
      number: 93,
      latin: "An-Nur",
      arabic: "النُّورُ",
      translationId: "Yang Maha Bercahaya",
    ),
    ModelAsmaulHusna(
      number: 94,
      latin: "Al-Hadi",
      arabic: "الْهَادِي",
      translationId: "Yang Maha Pemberi Petunjuk",
    ),
    ModelAsmaulHusna(
      number: 95,
      latin: "Al-Badi'",
      arabic: "الْبَدِيعُ",
      translationId: "Yang Maha Pencipta Keindahan",
    ),
    ModelAsmaulHusna(
      number: 96,
      latin: "Al-Baqi",
      arabic: "الْبَاقِي",
      translationId: "Yang Maha Kekal",
    ),
    ModelAsmaulHusna(
      number: 97,
      latin: "Al-Warits",
      arabic: "الْوَارِثُ",
      translationId: "Yang Maha Pewaris",
    ),
    ModelAsmaulHusna(
      number: 98,
      latin: "Ar-Rasyid",
      arabic: "الرَّشِيدُ",
      translationId: "Yang Maha Pandai",
    ),
    ModelAsmaulHusna(
      number: 99,
      latin: "Ash-Shabur",
      arabic: "الصَّبُورُ",
      translationId: "Yang Maha Sabar",
    ),
  ];
}
