class ModelHijaiyah {
  final int number;
  final String arabic;
  final String name;
  final String latin;
  final String makhraj;
  final String makhrajDesc;
  final String sifat;
  final String fathah;
  final String kasrah;
  final String dhammah;
  final String fathahRead;
  final String kasrahRead;
  final String dhammahRead;
  final String isolated;
  final String initial;
  final String medial;
  final String finalForm;
  final String exampleWord;
  final String exampleMeaning;
  final String categoryMakhraj;

  const ModelHijaiyah({
    required this.number,
    required this.arabic,
    required this.name,
    required this.latin,
    required this.makhraj,
    required this.makhrajDesc,
    required this.sifat,
    required this.fathah,
    required this.kasrah,
    required this.dhammah,
    required this.fathahRead,
    required this.kasrahRead,
    required this.dhammahRead,
    required this.isolated,
    required this.initial,
    required this.medial,
    required this.finalForm,
    required this.exampleWord,
    required this.exampleMeaning,
    required this.categoryMakhraj,
  });
}

class ModelHarakatInfo {
  final String name;
  final String symbol;
  final String sound;
  final String description;
  final String exampleArabic;
  final String exampleLatin;

  const ModelHarakatInfo({
    required this.name,
    required this.symbol,
    required this.sound,
    required this.description,
    required this.exampleArabic,
    required this.exampleLatin,
  });
}

class HijaiyahData {
  static const List<ModelHijaiyah> list = [
    ModelHijaiyah(
      number: 1,
      arabic: 'ا',
      name: 'Alif',
      latin: 'A / -',
      makhraj: 'Al-Jauf (Rongga Mulut & Tenggorokan)',
      makhrajDesc: 'Keluar dari rongga mulut dan tenggorokan terbuka sebagai pemanjang suara (Mad).',
      sifat: 'Jahar, Rakhawah, Istifal, Infitah',
      fathah: 'اَ',
      kasrah: 'اِ',
      dhammah: 'اُ',
      fathahRead: 'A',
      kasrahRead: 'I',
      dhammahRead: 'U',
      isolated: 'ا',
      initial: 'اـ',
      medial: 'ـاـ',
      finalForm: 'ـا',
      exampleWord: 'أَمَلٌ (Amalun)',
      exampleMeaning: 'Harapan / Cita-cita',
      categoryMakhraj: 'jauf',
    ),
    ModelHijaiyah(
      number: 2,
      arabic: 'ب',
      name: 'Ba\'',
      latin: 'B',
      makhraj: 'Asy-Syafatain (Dua Bibir)',
      makhrajDesc: 'Merapatkan kedua bibir (bibir atas dan bibir bawah) dengan kuat.',
      sifat: 'Jahar, Syiddah, Istifal, Infitah, Idzlaq, Qalqalah',
      fathah: 'بَ',
      kasrah: 'بِ',
      dhammah: 'بُ',
      fathahRead: 'Ba',
      kasrahRead: 'Bi',
      dhammahRead: 'Bu',
      isolated: 'ب',
      initial: 'بـ',
      medial: 'ـبـ',
      finalForm: 'ـب',
      exampleWord: 'بَابٌ (Baabun)',
      exampleMeaning: 'Pintu',
      categoryMakhraj: 'syafatain',
    ),
    ModelHijaiyah(
      number: 3,
      arabic: 'ت',
      name: 'Ta\'',
      latin: 'T',
      makhraj: 'Al-Lisan (Ujung Lidah)',
      makhrajDesc: 'Ujung lidah menempel pada pangkal gigi seri bagian atas.',
      sifat: 'Hams, Syiddah, Istifal, Infitah, Ishmat',
      fathah: 'تَ',
      kasrah: 'تِ',
      dhammah: 'تُ',
      fathahRead: 'Ta',
      kasrahRead: 'Ti',
      dhammahRead: 'Tu',
      isolated: 'ت',
      initial: 'تـ',
      medial: 'ـتـ',
      finalForm: 'ـت',
      exampleWord: 'تَمْرٌ (Tamrun)',
      exampleMeaning: 'Buah Kurma',
      categoryMakhraj: 'lisan',
    ),
    ModelHijaiyah(
      number: 4,
      arabic: 'ث',
      name: 'Tsa\'',
      latin: 'Ts',
      makhraj: 'Al-Lisan (Ujung Lidah)',
      makhrajDesc: 'Ujung lidah keluar sedikit dan bersentuhan dengan ujung dua gigi seri atas.',
      sifat: 'Hams, Rakhawah, Istifal, Infitah, Ishmat',
      fathah: 'ثَ',
      kasrah: 'ثِ',
      dhammah: 'ثُ',
      fathahRead: 'Tsa',
      kasrahRead: 'Tsi',
      dhammahRead: 'Tsu',
      isolated: 'ث',
      initial: 'ثـ',
      medial: 'ـثـ',
      finalForm: 'ـث',
      exampleWord: 'ثَمَرٌ (Tsamarun)',
      exampleMeaning: 'Buah-buahan',
      categoryMakhraj: 'lisan',
    ),
    ModelHijaiyah(
      number: 5,
      arabic: 'ج',
      name: 'Jim',
      latin: 'J',
      makhraj: 'Al-Lisan (Tengah Lidah)',
      makhrajDesc: 'Tengah lidah bertemu dengan langit-langit mulut bagian atas.',
      sifat: 'Jahar, Syiddah, Istifal, Infitah, Ishmat, Qalqalah',
      fathah: 'جَ',
      kasrah: 'جِ',
      dhammah: 'جُ',
      fathahRead: 'Ja',
      kasrahRead: 'Ji',
      dhammahRead: 'Ju',
      isolated: 'ج',
      initial: 'جـ',
      medial: 'ـجـ',
      finalForm: 'ـج',
      exampleWord: 'جَمَلٌ (Jamalun)',
      exampleMeaning: 'Unta',
      categoryMakhraj: 'lisan',
    ),
    ModelHijaiyah(
      number: 6,
      arabic: 'ح',
      name: 'Ha\' (Kecil)',
      latin: 'H (Bersih)',
      makhraj: 'Al-Halq (Tengah Tenggorokan)',
      makhrajDesc: 'Keluar dari pertengahan tenggorokan dengan hembusan nafas bersih dan halus.',
      sifat: 'Hams, Rakhawah, Istifal, Infitah, Ishmat',
      fathah: 'حَ',
      kasrah: 'حِ',
      dhammah: 'حُ',
      fathahRead: 'Ha',
      kasrahRead: 'Hi',
      dhammahRead: 'Hu',
      isolated: 'ح',
      initial: 'حـ',
      medial: 'ـحـ',
      finalForm: 'ـح',
      exampleWord: 'حَمْدٌ (Hamdun)',
      exampleMeaning: 'Pujian',
      categoryMakhraj: 'halq',
    ),
    ModelHijaiyah(
      number: 7,
      arabic: 'خ',
      name: 'Kha\'',
      latin: 'Kh',
      makhraj: 'Al-Halq (Ujung Tenggorokan Atas)',
      makhrajDesc: 'Keluar dari tenggorokan paling atas dekat pangkal lidah, berbunyi serak/khas.',
      sifat: 'Hams, Rakhawah, Isti\'la, Infitah, Ishmat',
      fathah: 'خَ',
      kasrah: 'خِ',
      dhammah: 'خُ',
      fathahRead: 'Kha',
      kasrahRead: 'Khi',
      dhammahRead: 'Khu',
      isolated: 'خ',
      initial: 'خـ',
      medial: 'ـخـ',
      finalForm: 'ـخ',
      exampleWord: 'خَبَرٌ (Khabarun)',
      exampleMeaning: 'Berita / Kabar',
      categoryMakhraj: 'halq',
    ),
    ModelHijaiyah(
      number: 8,
      arabic: 'د',
      name: 'Dal',
      latin: 'D',
      makhraj: 'Al-Lisan (Ujung Lidah)',
      makhrajDesc: 'Ujung lidah menempel pada pangkal gigi seri atas.',
      sifat: 'Jahar, Syiddah, Istifal, Infitah, Ishmat, Qalqalah',
      fathah: 'دَ',
      kasrah: 'دِ',
      dhammah: 'دُ',
      fathahRead: 'Da',
      kasrahRead: 'Di',
      dhammahRead: 'Du',
      isolated: 'د',
      initial: 'دـ',
      medial: 'ـدـ',
      finalForm: 'ـد',
      exampleWord: 'دَرْسٌ (Darsun)',
      exampleMeaning: 'Pelajaran',
      categoryMakhraj: 'lisan',
    ),
    ModelHijaiyah(
      number: 9,
      arabic: 'ذ',
      name: 'Dzal',
      latin: 'Dz',
      makhraj: 'Al-Lisan (Ujung Lidah)',
      makhrajDesc: 'Ujung lidah keluar sedikit dan bersentuhan dengan ujung dua gigi seri atas.',
      sifat: 'Jahar, Rakhawah, Istifal, Infitah, Ishmat',
      fathah: 'ذَ',
      kasrah: 'ذِ',
      dhammah: 'ذُ',
      fathahRead: 'Dza',
      kasrahRead: 'Dzi',
      dhammahRead: 'Dzu',
      isolated: 'ذ',
      initial: 'ذـ',
      medial: 'ـذـ',
      finalForm: 'ـذ',
      exampleWord: 'ذِكْرٌ (Dzikrun)',
      exampleMeaning: 'Mengingat / Dzikir',
      categoryMakhraj: 'lisan',
    ),
    ModelHijaiyah(
      number: 10,
      arabic: 'ر',
      name: 'Ra\'',
      latin: 'R',
      makhraj: 'Al-Lisan (Ujung Lidah)',
      makhrajDesc: 'Ujung lidah agak ke dalam menyentuh gusi gigi seri atas dengan getaran ringan.',
      sifat: 'Jahar, Tawassuth, Istifal, Infitah, Idzlaq, Inhiraf, Takrir',
      fathah: 'رَ',
      kasrah: 'رِ',
      dhammah: 'رُ',
      fathahRead: 'Ra',
      kasrahRead: 'Ri',
      dhammahRead: 'Ru',
      isolated: 'ر',
      initial: 'رـ',
      medial: 'ـرـ',
      finalForm: 'ـر',
      exampleWord: 'رَحْمَةٌ (Rahmatun)',
      exampleMeaning: 'Kasih Sayang / Rahmat',
      categoryMakhraj: 'lisan',
    ),
    ModelHijaiyah(
      number: 11,
      arabic: 'ز',
      name: 'Zai',
      latin: 'Z',
      makhraj: 'Al-Lisan (Ujung Lidah)',
      makhrajDesc: 'Ujung lidah mendekat ke antara gigi seri atas dan bawah dengan desis tajam (Shafir).',
      sifat: 'Jahar, Rakhawah, Istifal, Infitah, Ishmat, Shafir',
      fathah: 'زَ',
      kasrah: 'زِ',
      dhammah: 'زُ',
      fathahRead: 'Za',
      kasrahRead: 'Zi',
      dhammahRead: 'Zu',
      isolated: 'ز',
      initial: 'زـ',
      medial: 'ـزـ',
      finalForm: 'ـز',
      exampleWord: 'زَهْرَةٌ (Zahratun)',
      exampleMeaning: 'Bunga',
      categoryMakhraj: 'lisan',
    ),
    ModelHijaiyah(
      number: 12,
      arabic: 'س',
      name: 'Sin',
      latin: 'S',
      makhraj: 'Al-Lisan (Ujung Lidah)',
      makhrajDesc: 'Ujung lidah berada di belakang gigi seri bawah dengan desis nafas lembut.',
      sifat: 'Hams, Rakhawah, Istifal, Infitah, Ishmat, Shafir',
      fathah: 'سَ',
      kasrah: 'سِ',
      dhammah: 'سُ',
      fathahRead: 'Sa',
      kasrahRead: 'Si',
      dhammahRead: 'Su',
      isolated: 'س',
      initial: 'سـ',
      medial: 'ـسـ',
      finalForm: 'ـس',
      exampleWord: 'سَلَامٌ (Salaamun)',
      exampleMeaning: 'Kedamaian / Keselamatan',
      categoryMakhraj: 'lisan',
    ),
    ModelHijaiyah(
      number: 13,
      arabic: 'ش',
      name: 'Syin',
      latin: 'Sy',
      makhraj: 'Al-Lisan (Tengah Lidah)',
      makhrajDesc: 'Tengah lidah naik mendekati langit-langit mulut dengan hembusan angin menyebar (Tafasysyi).',
      sifat: 'Hams, Rakhawah, Istifal, Infitah, Ishmat, Tafasysyi',
      fathah: 'شَ',
      kasrah: 'شِ',
      dhammah: 'شُ',
      fathahRead: 'Sya',
      kasrahRead: 'Syi',
      dhammahRead: 'Syu',
      isolated: 'ش',
      initial: 'شـ',
      medial: 'ـشـ',
      finalForm: 'ـش',
      exampleWord: 'شَمْسٌ (Syamsun)',
      exampleMeaning: 'Matahari',
      categoryMakhraj: 'lisan',
    ),
    ModelHijaiyah(
      number: 14,
      arabic: 'ص',
      name: 'Shad',
      latin: 'Sh (Tebal)',
      makhraj: 'Al-Lisan (Ujung Lidah)',
      makhrajDesc: 'Ujung lidah di gigi seri bawah dengan pangkal lidah terangkat tebal (Ithbaq).',
      sifat: 'Hams, Rakhawah, Isti\'la, Ithbaq, Ishmat, Shafir',
      fathah: 'صَ',
      kasrah: 'صِ',
      dhammah: 'صُ',
      fathahRead: 'Sha',
      kasrahRead: 'Shi',
      dhammahRead: 'Shu',
      isolated: 'ص',
      initial: 'صـ',
      medial: 'ـصـ',
      finalForm: 'ـص',
      exampleWord: 'صَبْرٌ (Shabrun)',
      exampleMeaning: 'Kesabaran',
      categoryMakhraj: 'lisan',
    ),
    ModelHijaiyah(
      number: 15,
      arabic: 'ض',
      name: 'Dhad',
      latin: 'Dh (Tebal)',
      makhraj: 'Al-Lisan (Tepi / Sisi Lidah)',
      makhrajDesc: 'Salah satu atau kedua tepi lidah dirapatkan ke deretan gigi geraham atas.',
      sifat: 'Jahar, Rakhawah, Isti\'la, Ithbaq, Ishmat, Istithalah',
      fathah: 'ضَ',
      kasrah: 'ضِ',
      dhammah: 'ضُ',
      fathahRead: 'Dha',
      kasrahRead: 'Dhi',
      dhammahRead: 'Dhu',
      isolated: 'ض',
      initial: 'ضـ',
      medial: 'ـضـ',
      finalForm: 'ـض',
      exampleWord: 'ضَوْءٌ (Dhou\'un)',
      exampleMeaning: 'Cahaya / Penerangan',
      categoryMakhraj: 'lisan',
    ),
    ModelHijaiyah(
      number: 16,
      arabic: 'ط',
      name: 'Tha\'',
      latin: 'Th (Tebal)',
      makhraj: 'Al-Lisan (Ujung Lidah)',
      makhrajDesc: 'Ujung lidah menempel kuat pada pangkal gigi seri atas dengan pangkal lidah naik tebal.',
      sifat: 'Jahar, Syiddah, Isti\'la, Ithbaq, Ishmat, Qalqalah',
      fathah: 'طَ',
      kasrah: 'طِ',
      dhammah: 'طُ',
      fathahRead: 'Tha',
      kasrahRead: 'Thi',
      dhammahRead: 'Thu',
      isolated: 'ط',
      initial: 'طـ',
      medial: 'ـطـ',
      finalForm: 'ـط',
      exampleWord: 'طَيْرٌ (Thayrun)',
      exampleMeaning: 'Burung',
      categoryMakhraj: 'lisan',
    ),
    ModelHijaiyah(
      number: 17,
      arabic: 'ظ',
      name: 'Zha\'',
      latin: 'Zh (Tebal)',
      makhraj: 'Al-Lisan (Ujung Lidah)',
      makhrajDesc: 'Ujung lidah keluar sedikit menyentuh ujung gigi seri atas dengan suara tebal.',
      sifat: 'Jahar, Rakhawah, Isti\'la, Ithbaq, Ishmat',
      fathah: 'ظَ',
      kasrah: 'ظِ',
      dhammah: 'ظُ',
      fathahRead: 'Zha',
      kasrahRead: 'Zhi',
      dhammahRead: 'Zhu',
      isolated: 'ظ',
      initial: 'ظـ',
      medial: 'ـظـ',
      finalForm: 'ـظ',
      exampleWord: 'ظِلٌّ (Zhillun)',
      exampleMeaning: 'Bayangan / Naungan',
      categoryMakhraj: 'lisan',
    ),
    ModelHijaiyah(
      number: 18,
      arabic: 'ع',
      name: '\'Ain',
      latin: '\'A',
      makhraj: 'Al-Halq (Tengah Tenggorokan)',
      makhrajDesc: 'Keluar dari pertengahan tenggorokan dengan suara lembut tertekan.',
      sifat: 'Jahar, Tawassuth, Istifal, Infitah, Ishmat',
      fathah: 'عَ',
      kasrah: 'عِ',
      dhammah: 'عُ',
      fathahRead: '\'A',
      kasrahRead: '\'I',
      dhammahRead: '\'U',
      isolated: 'ع',
      initial: 'عـ',
      medial: 'ـعـ',
      finalForm: 'ـع',
      exampleWord: 'عِلْمٌ (\'Ilmun)',
      exampleMeaning: 'Ilmu Pengetahuan',
      categoryMakhraj: 'halq',
    ),
    ModelHijaiyah(
      number: 19,
      arabic: 'غ',
      name: 'Ghain',
      latin: 'Gh',
      makhraj: 'Al-Halq (Ujung Tenggorokan Atas)',
      makhrajDesc: 'Keluar dari ujung tenggorokan paling atas mendekati anak lidah.',
      sifat: 'Jahar, Rakhawah, Isti\'la, Infitah, Ishmat',
      fathah: 'غَ',
      kasrah: 'غِ',
      dhammah: 'غُ',
      fathahRead: 'Gha',
      kasrahRead: 'Ghi',
      dhammahRead: 'Ghu',
      isolated: 'غ',
      initial: 'غـ',
      medial: 'ـغـ',
      finalForm: 'ـغ',
      exampleWord: 'غَيْبٌ (Ghaybun)',
      exampleMeaning: 'Perkara Gaib',
      categoryMakhraj: 'halq',
    ),
    ModelHijaiyah(
      number: 20,
      arabic: 'ف',
      name: 'Fa\'',
      latin: 'F',
      makhraj: 'Asy-Syafatain (Bibir Bawah)',
      makhrajDesc: 'Ujung dua gigi seri atas menempel pada bagian dalam bibir bawah.',
      sifat: 'Hams, Rakhawah, Istifal, Infitah, Idzlaq',
      fathah: 'فَ',
      kasrah: 'فِ',
      dhammah: 'فُ',
      fathahRead: 'Fa',
      kasrahRead: 'Fi',
      dhammahRead: 'Fu',
      isolated: 'ف',
      initial: 'فـ',
      medial: 'ـفـ',
      finalForm: 'ـف',
      exampleWord: 'فَجْرٌ (Fajrun)',
      exampleMeaning: 'Waktu Fajar / Shubuh',
      categoryMakhraj: 'syafatain',
    ),
    ModelHijaiyah(
      number: 21,
      arabic: 'ق',
      name: 'Qaf',
      latin: 'Q',
      makhraj: 'Al-Lisan (Pangkal Lidah Belakang)',
      makhrajDesc: 'Pangkal lidah paling belakang menempel pada langit-langit lunak bagian atas.',
      sifat: 'Jahar, Syiddah, Isti\'la, Infitah, Ishmat, Qalqalah',
      fathah: 'قَ',
      kasrah: 'قِ',
      dhammah: 'قُ',
      fathahRead: 'Qa',
      kasrahRead: 'Qi',
      dhammahRead: 'Qu',
      isolated: 'ق',
      initial: 'قـ',
      medial: 'ـقـ',
      finalForm: 'ـق',
      exampleWord: 'قَلْبٌ (Qalbun)',
      exampleMeaning: 'Hati / Qalbu',
      categoryMakhraj: 'lisan',
    ),
    ModelHijaiyah(
      number: 22,
      arabic: 'ك',
      name: 'Kaf',
      latin: 'K',
      makhraj: 'Al-Lisan (Pangkal Lidah Depan Qaf)',
      makhrajDesc: 'Pangkal lidah sedikit di depan huruf Qaf menempel ke langit-langit keras dengan hembusan nafas.',
      sifat: 'Hams, Syiddah, Istifal, Infitah, Ishmat',
      fathah: 'كَ',
      kasrah: 'كِ',
      dhammah: 'كُ',
      fathahRead: 'Ka',
      kasrahRead: 'Ki',
      dhammahRead: 'Ku',
      isolated: 'ك',
      initial: 'كـ',
      medial: 'ـكـ',
      finalForm: 'ـك',
      exampleWord: 'كِتَابٌ (Kitaabun)',
      exampleMeaning: 'Buku / Kitab',
      categoryMakhraj: 'lisan',
    ),
    ModelHijaiyah(
      number: 23,
      arabic: 'ل',
      name: 'Lam',
      latin: 'L',
      makhraj: 'Al-Lisan (Tepi Ujung Lidah)',
      makhrajDesc: 'Tepi ujung lidah menyentuh gusi gigi seri atas.',
      sifat: 'Jahar, Tawassuth, Istifal, Infitah, Idzlaq, Inhiraf',
      fathah: 'لَ',
      kasrah: 'لِ',
      dhammah: 'لُ',
      fathahRead: 'La',
      kasrahRead: 'Li',
      dhammahRead: 'Lu',
      isolated: 'ل',
      initial: 'لـ',
      medial: 'ـلـ',
      finalForm: 'ـل',
      exampleWord: 'لَيْلٌ (Laylun)',
      exampleMeaning: 'Malam Hari',
      categoryMakhraj: 'lisan',
    ),
    ModelHijaiyah(
      number: 24,
      arabic: 'م',
      name: 'Mim',
      latin: 'M',
      makhraj: 'Asy-Syafatain (Dua Bibir)',
      makhrajDesc: 'Merapatkan kedua bibir secara wajar disertai dengung (Ghunnah) dari hidung.',
      sifat: 'Jahar, Tawassuth, Istifal, Infitah, Idzlaq, Ghunnah',
      fathah: 'مَ',
      kasrah: 'مِ',
      dhammah: 'مُ',
      fathahRead: 'Ma',
      kasrahRead: 'Mi',
      dhammahRead: 'Mu',
      isolated: 'م',
      initial: 'مـ',
      medial: 'ـمـ',
      finalForm: 'ـم',
      exampleWord: 'مَسْجِدٌ (Masjidun)',
      exampleMeaning: 'Masjid / Tempat Sujud',
      categoryMakhraj: 'syafatain',
    ),
    ModelHijaiyah(
      number: 25,
      arabic: 'ن',
      name: 'Nun',
      latin: 'N',
      makhraj: 'Al-Lisan & Al-Khaisyum',
      makhrajDesc: 'Ujung lidah menempel gusi atas dengan dengung (Ghunnah) dari pangkal hidung.',
      sifat: 'Jahar, Tawassuth, Istifal, Infitah, Idzlaq, Ghunnah',
      fathah: 'نَ',
      kasrah: 'نِ',
      dhammah: 'نُ',
      fathahRead: 'Na',
      kasrahRead: 'Ni',
      dhammahRead: 'Nu',
      isolated: 'ن',
      initial: 'نـ',
      medial: 'ـنـ',
      finalForm: 'ـن',
      exampleWord: 'نُوْرٌ (Nuurun)',
      exampleMeaning: 'Cahaya / Sinar',
      categoryMakhraj: 'lisan',
    ),
    ModelHijaiyah(
      number: 26,
      arabic: 'و',
      name: 'Waw',
      latin: 'W',
      makhraj: 'Asy-Syafatain (Dua Bibir Membulat)',
      makhrajDesc: 'Memonyongkan kedua bibir ke depan dengan menyisakan sedikit rongga udara.',
      sifat: 'Jahar, Rakhawah, Istifal, Infitah, Ishmat, Liin',
      fathah: 'وَ',
      kasrah: 'وِ',
      dhammah: 'وُ',
      fathahRead: 'Wa',
      kasrahRead: 'Wi',
      dhammahRead: 'Wu',
      isolated: 'و',
      initial: 'وـ',
      medial: 'ـوـ',
      finalForm: 'ـو',
      exampleWord: 'وَرْدَةٌ (Wardatun)',
      exampleMeaning: 'Bunga Mawar',
      categoryMakhraj: 'syafatain',
    ),
    ModelHijaiyah(
      number: 27,
      arabic: 'هـ',
      name: 'Ha\' (Besar)',
      latin: 'H (Dada)',
      makhraj: 'Al-Halq (Pangkal Tenggorokan)',
      makhrajDesc: 'Keluar dari pangkal tenggorokan paling dalam (dekat rongga dada).',
      sifat: 'Hams, Rakhawah, Istifal, Infitah, Ishmat',
      fathah: 'هَ',
      kasrah: 'هِ',
      dhammah: 'هُ',
      fathahRead: 'Ha',
      kasrahRead: 'Hi',
      dhammahRead: 'Hu',
      isolated: 'ه',
      initial: 'هـ',
      medial: 'ـهـ',
      finalForm: 'ـه',
      exampleWord: 'هُدًى (Hudan)',
      exampleMeaning: 'Petunjuk',
      categoryMakhraj: 'halq',
    ),
    ModelHijaiyah(
      number: 28,
      arabic: 'لا',
      name: 'Lam Alif',
      latin: 'Laa',
      makhraj: 'Al-Jauf & Al-Lisan',
      makhrajDesc: 'Gabungan huruf Lam pada lidah dan Alif mad pada rongga mulut.',
      sifat: 'Jahar, Tawassuth, Istifal, Infitah',
      fathah: 'لَا',
      kasrah: 'لِيْ',
      dhammah: 'لُوْ',
      fathahRead: 'Laa',
      kasrahRead: 'Lii',
      dhammahRead: 'Luu',
      isolated: 'لا',
      initial: 'لاـ',
      medial: 'ـلاـ',
      finalForm: 'ـلا',
      exampleWord: 'لَا إِلَهَ (Laa Ilaaha)',
      exampleMeaning: 'Tiada Sesembahan',
      categoryMakhraj: 'jauf',
    ),
    ModelHijaiyah(
      number: 29,
      arabic: 'ء',
      name: 'Hamzah',
      latin: '\'',
      makhraj: 'Al-Halq (Pangkal Tenggorokan)',
      makhrajDesc: 'Keluar dari pangkal tenggorokan terdalam dengan tekanan suara tegas.',
      sifat: 'Jahar, Syiddah, Istifal, Infitah, Ishmat',
      fathah: 'أَ',
      kasrah: 'إِ',
      dhammah: 'أُ',
      fathahRead: '\'A',
      kasrahRead: '\'I',
      dhammahRead: '\'U',
      isolated: 'ء',
      initial: 'أـ',
      medial: 'ـأـ',
      finalForm: 'ـأ',
      exampleWord: 'أَمَانٌ (Amaanun)',
      exampleMeaning: 'Keamanan / Rasa Aman',
      categoryMakhraj: 'halq',
    ),
    ModelHijaiyah(
      number: 30,
      arabic: 'ي',
      name: 'Ya\'',
      latin: 'Y',
      makhraj: 'Al-Lisan (Tengah Lidah)',
      makhrajDesc: 'Tengah lidah terangkat ke langit-langit tanpa menyentuh rapat.',
      sifat: 'Jahar, Rakhawah, Istifal, Infitah, Ishmat, Liin',
      fathah: 'يَ',
      kasrah: 'يِ',
      dhammah: 'يُ',
      fathahRead: 'Ya',
      kasrahRead: 'Yi',
      dhammahRead: 'Yu',
      isolated: 'ي',
      initial: 'يـ',
      medial: 'ـيـ',
      finalForm: 'ـي',
      exampleWord: 'يَوْمٌ (Yawmun)',
      exampleMeaning: 'Hari',
      categoryMakhraj: 'lisan',
    ),
  ];

  static const List<ModelHarakatInfo> harakatList = [
    ModelHarakatInfo(
      name: 'Fathah (فَتْحَة)',
      symbol: 'ـَ',
      sound: 'Bunyi Vokal "A"',
      description: 'Garis miring di atas huruf hijaiyah. Huruf berharakat fathah dibaca vokal "A" dengan membuka mulut secara wajar.',
      exampleArabic: 'بَ - تَ - ثَ',
      exampleLatin: 'Ba - Ta - Tsa',
    ),
    ModelHarakatInfo(
      name: 'Kasrah (كَسْرَة)',
      symbol: 'ـِ',
      sound: 'Bunyi Vokal "I"',
      description: 'Garis miring di bawah huruf hijaiyah. Huruf berharakat kasrah dibaca vokal "I" dengan menurunkan rahang bawah sedikit.',
      exampleArabic: 'بِ - تِ - ثِ',
      exampleLatin: 'Bi - Ti - Tsi',
    ),
    ModelHarakatInfo(
      name: 'Dhammah (ضَمَّة)',
      symbol: 'ـُ',
      sound: 'Bunyi Vokal "U"',
      description: 'Tanda menyerupai huruf waw kecil di atas huruf. Dibaca vokal "U" dengan memonyongkan kedua bibir.',
      exampleArabic: 'بُ - تُ - ثُ',
      exampleLatin: 'Bu - Tu - Tsu',
    ),
    ModelHarakatInfo(
      name: 'Fathatain / Tanwin Fathah (فَتْحَتَيْن)',
      symbol: 'ـً',
      sound: 'Bunyi "AN"',
      description: 'Dua garis miring di atas huruf. Menghasilkan bunyi akhir "an" (seperti ada huruf nun sukun di ujungnya).',
      exampleArabic: 'بًا - تًا - ثًا',
      exampleLatin: 'Ban - Tan - Tsan',
    ),
    ModelHarakatInfo(
      name: 'Kasratain / Tanwin Kasrah (كَسْرَتَيْن)',
      symbol: 'ـٍ',
      sound: 'Bunyi "IN"',
      description: 'Dua garis miring di bawah huruf. Menghasilkan bunyi akhir "in".',
      exampleArabic: 'بٍ - تٍ - ثٍ',
      exampleLatin: 'Bin - Tin - Tsin',
    ),
    ModelHarakatInfo(
      name: 'Dhammatain / Tanwin Dhammah (ضَمَّتَيْن)',
      symbol: 'ـٌ',
      sound: 'Bunyi "UN"',
      description: 'Tanda ganda dhammah di atas huruf. Menghasilkan bunyi akhir "un".',
      exampleArabic: 'بٌ - تٌ - ثٌ',
      exampleLatin: 'Bun - Tun - Tsun',
    ),
    ModelHarakatInfo(
      name: 'Sukun / Tanda Mati (سُكُوْن)',
      symbol: 'ـْ',
      sound: 'Mati / Konsonan Murni',
      description: 'Lingkaran kecil di atas huruf yang menandakan huruf tersebut tidak bervokal / mati.',
      exampleArabic: 'أَبْ - أَتْ - أَثْ',
      exampleLatin: 'Ab - At - Ats',
    ),
    ModelHarakatInfo(
      name: 'Tasydid / Syaddah (تَشْدِيْد)',
      symbol: 'ـّ',
      sound: 'Ganda / Ditekan (Double Consonant)',
      description: 'Tanda menyerupai huruf w / kepala sin kecil di atas huruf. Menandakan huruf dibaca ganda dan ditekan.',
      exampleArabic: 'رَبَّ - حَقَّ - عَدَّ',
      exampleLatin: 'Rabba - Haqqa - \'Adda',
    ),
  ];

  static const List<Map<String, String>> makhrajCategories = [
    {
      'id': 'all',
      'name': 'Semua Huruf',
      'arabic': 'كُلُّ الحُرُوفِ',
      'desc': '30 Huruf Hijaiyah Lengkap',
    },
    {
      'id': 'halq',
      'name': 'Al-Halq (Tenggorokan)',
      'arabic': 'الحَلْق',
      'desc': 'ء, هـ, ع, ح, غ, خ (6 Huruf)',
    },
    {
      'id': 'lisan',
      'name': 'Al-Lisan (Lidah)',
      'arabic': 'اللِّسَان',
      'desc': 'ق, ك, ج, ش, ي, ض, ل, ن, ر, ط, د, ت, ص, ز, س, ظ, ذ, ث (18 Huruf)',
    },
    {
      'id': 'syafatain',
      'name': 'Asy-Syafatain (Dua Bibir)',
      'arabic': 'الشَّفَتَيْن',
      'desc': 'ف, ب, م, و (4 Huruf)',
    },
    {
      'id': 'jauf',
      'name': 'Al-Jauf (Rongga Mulut)',
      'arabic': 'الجَوْف',
      'desc': 'ا, لا (Huruf Mad / Pemanjang)',
    },
  ];
}
